-- ============================================================
-- ExaFinvest Market Database
-- Canonical Production Database Schema
-- PostgreSQL
-- ============================================================
--
-- Tables:
--   1. instruments
--   2. ticks
--   3. candles
--   4. indicators
--   5. system_events
--
-- Data flow:
--
--   instruments
--        |
--        +----> ticks
--        |
--        +----> candles
--                    |
--                    +----> indicators
--
-- ============================================================


-- ============================================================
-- 1. INSTRUMENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS instruments (

    instrument_id BIGSERIAL PRIMARY KEY,

    symbol VARCHAR(100) NOT NULL,

    exchange VARCHAR(20) NOT NULL DEFAULT 'NSE',

    isin VARCHAR(20),

    provider VARCHAR(50),

    provider_instrument_id VARCHAR(100),

    provider_symbol VARCHAR(100),

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_instrument_symbol_exchange
        UNIQUE (symbol, exchange),

    CONSTRAINT uq_provider_instrument
        UNIQUE (provider, provider_instrument_id)
);


-- ============================================================
-- INSTRUMENT INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_instruments_active
    ON instruments (active);

CREATE INDEX IF NOT EXISTS idx_instruments_provider
    ON instruments (provider);

CREATE INDEX IF NOT EXISTS idx_instruments_provider_id
    ON instruments (provider_instrument_id);


-- ============================================================
-- 2. TICKS
-- ============================================================

CREATE TABLE IF NOT EXISTS ticks (

    tick_id BIGSERIAL PRIMARY KEY,

    instrument_id BIGINT NOT NULL,

    timestamp TIMESTAMPTZ NOT NULL,

    last_price NUMERIC(18, 6),

    last_quantity BIGINT,

    volume BIGINT,

    bid_price NUMERIC(18, 6),

    ask_price NUMERIC(18, 6),

    open_price NUMERIC(18, 6),

    high_price NUMERIC(18, 6),

    low_price NUMERIC(18, 6),

    previous_close NUMERIC(18, 6),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_ticks_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES instruments(instrument_id)
        ON DELETE CASCADE
);


-- ============================================================
-- TICK INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_ticks_instrument_timestamp
    ON ticks (
        instrument_id,
        timestamp DESC
    );

CREATE INDEX IF NOT EXISTS idx_ticks_timestamp
    ON ticks (
        timestamp DESC
    );

-- Canonical market-state uniqueness.
--
-- A repeated Upstox trade state is identified by:
--
--   instrument_id
--   timestamp
--   last_price
--   last_quantity
--   volume
--
-- Quote fields such as bid_price and ask_price are mutable
-- snapshot data and therefore are NOT part of the canonical
-- uniqueness key.
--
-- NULLS NOT DISTINCT ensures PostgreSQL treats NULL values
-- in the canonical key as equal for uniqueness purposes.

CREATE UNIQUE INDEX IF NOT EXISTS uq_ticks_market_snapshot
    ON ticks (
        instrument_id,
        timestamp,
        last_price,
        last_quantity,
        volume
    )
    NULLS NOT DISTINCT;


-- ============================================================
-- 3. CANDLES
-- ============================================================

CREATE TABLE IF NOT EXISTS candles (

    candle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    instrument_id BIGINT NOT NULL,

    timestamp TIMESTAMPTZ NOT NULL,

    timeframe VARCHAR(20) NOT NULL DEFAULT '1m',

    open_price NUMERIC(18, 6),

    high_price NUMERIC(18, 6),

    low_price NUMERIC(18, 6),

    close_price NUMERIC(18, 6),

    volume BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_candles_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES instruments(instrument_id),

    CONSTRAINT uq_candle_instrument_timestamp_timeframe
        UNIQUE (
            instrument_id,
            timestamp,
            timeframe
        )
);


-- ============================================================
-- CANDLE INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_candles_instrument_timeframe_timestamp
    ON candles (
        instrument_id,
        timeframe,
        timestamp DESC
    );


-- ============================================================
-- 4. INDICATORS
-- ============================================================

CREATE TABLE IF NOT EXISTS indicators (

    indicator_id BIGSERIAL PRIMARY KEY,

    instrument_id BIGINT NOT NULL,

    timestamp TIMESTAMPTZ NOT NULL,

    timeframe VARCHAR(20) NOT NULL DEFAULT '1m',

    rsi_14 NUMERIC(18, 6),

    ema_9 NUMERIC(18, 6),

    ema_20 NUMERIC(18, 6),

    ema_50 NUMERIC(18, 6),

    vwap NUMERIC(18, 6),

    atr_14 NUMERIC(18, 6),

    volume_sma_20 NUMERIC(18, 6),

    macd NUMERIC(18, 6),

    macd_signal NUMERIC(18, 6),

    macd_histogram NUMERIC(18, 6),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_indicators_instrument
        FOREIGN KEY (instrument_id)
        REFERENCES instruments(instrument_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_indicator_instrument_timestamp_timeframe
        UNIQUE (
            instrument_id,
            timestamp,
            timeframe
        )
);


-- ============================================================
-- INDICATOR INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_indicators_instrument_timestamp
    ON indicators (
        instrument_id,
        timestamp DESC
    );

CREATE INDEX IF NOT EXISTS idx_indicators_timestamp
    ON indicators (
        timestamp DESC
    );


-- ============================================================
-- 5. SYSTEM EVENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS system_events (

    event_id BIGSERIAL PRIMARY KEY,

    event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    event_type VARCHAR(100) NOT NULL,

    provider VARCHAR(50),

    severity VARCHAR(20) NOT NULL DEFAULT 'INFO',

    message TEXT,

    details JSONB
);


-- ============================================================
-- SYSTEM EVENT INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_system_events_time
    ON system_events (
        event_time DESC
    );

CREATE INDEX IF NOT EXISTS idx_system_events_type
    ON system_events (
        event_type
    );


-- ============================================================
-- END OF SCHEMA
-- ============================================================